#spring.application.name=OnlineLibrary

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/online_library
spring.datasource.username=online_library
spring.datasource.password=online_library

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect